---
# tasks file for ansible-vscode

- name: Ensure vscode is installed
  community.general.homebrew:
    name: "visual-studio-code"
    state: installed
  when: ansible_distribution == "MacOSX"

# TODO:
# configure vscode dotfiles and extensions via ansible
# make everything platform independent
#
# return list of installed extensions:
# code --list-extensions
#
# install extension:
# code --install-extension <extension>
#
# uninstall extension:
# code --uninstall-extension <extension>
#
# dotfiles:
# ~/Library/Application\ Support/Code/User/settings.json
